In [1]:
#import numpy
import numpy as np

#Practice generating arrays filled with random numbers
np.random.seed(100)
arr1d = np.random.randint(5, 20, size = 10) #create a one-dimentional array consisting of 10 integers between [5, 20)
arr2d = np.random.randint(100, size = (6, 8)) #create two dimentional 6*8 array consisting of 48 integers between [0, 100)
print("The one dimentional random array looks like this: \n", arr1d)
print("The two dimentional random array looks like this: \n", arr2d)

The one dimentional random array looks like this: 
 [13 13  8 12 12  5 15 19  9  7]
The two dimentional random array looks like this: 
 [[53 66 98 14 34 24 15 60]
 [58 16  9 93 86  2 27  4]
 [31  1 13 83  4 91 59 67]
 [ 7 49 47 65 61 14 55 71]
 [80  2 94 19 98 63 53 27]
 [56 30 48 47 39 38 44 18]]


In [2]:
#Some indexing on the arrays
print(arr1d[0]) #The first element of arr1d
print(arr1d[-5]) #The fifth element (from the back) in arr1d
print(arr2d[1, 1]) #The element in the second row and the second column of arr2d

13
5
16


In [3]:
#Subarrays in a one-dimensional array
print(arr1d[1:7:2]) #Starting with the second element of arr1d, and end with the seventh element; slice every other number
print(arr1d[5:]) #Every element after the sixth element
print(arr1d[:5]) #Access every element up to the fifth element
print(arr1d[::2]) #Every other element, starting from the first element
print(arr1d[1::2]) #Every other element, starting from the second element
print(arr1d[::-2]) #Every other element in reverse

[13 12  5]
[ 5 15 19  9  7]
[13 13  8 12 12]
[13  8 12 15  9]
[13 12  5 19  7]
[ 7 19  5 12 13]


In [4]:
#Subarrays in a two-dimensional array
print(arr2d[:2, :3]) #The first two rows and the first three columns
print(arr2d[::2, :3]) #Every other row starting from the first row, first three columns
print(arr2d[0]) #Shortcut for first row
print(arr2d[:, 0]) #First column
print(arr2d > 50) #A boolean mask of all numbers above 50
print(arr2d[arr2d > 50]) #returns all numbers above 50 in the array

[[53 66 98]
 [58 16  9]]
[[53 66 98]
 [31  1 13]
 [80  2 94]]
[53 66 98 14 34 24 15 60]
[53 58 31  7 80 56]
[[ True  True  True False False False False  True]
 [ True False False  True  True False False False]
 [False False False  True False  True  True  True]
 [False False False  True  True False  True  True]
 [ True False  True False  True  True  True False]
 [ True False False False False False False False]]
[53 66 98 60 58 93 86 83 91 59 67 65 61 55 71 80 94 98 63 53 56]


In [5]:
#other array functions
some_grid = np.array([[1, 2, 3], [4, 5, 6]])
other_grid = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.concatenate([some_grid, some_grid])) #concatenating grids vertically
print(np.concatenate([some_grid, other_grid])) #concatenating grids vertically
print(np.vstack([some_grid, some_grid + 1])) #stacking vertically
print(np.hstack([some_grid, some_grid + 2])) #"stack" horizotally

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
[[1 2 3 3 4 5]
 [4 5 6 6 7 8]]


In [6]:
#Pandas and series
import pandas as pd
s1 = pd.Series([1, 2, 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e'])
print(s1)
print(s1[1]) #The second row of s1
print(s1['a']) #The first row of s1 (indexed 'a1')
print(s1[(s1 > 1) & (s1 <5)]) #Masking elements in a series

a    1
b    2
c    3
d    4
e    5
dtype: int64
2
1
b    2
c    3
d    4
dtype: int64


In [7]:
#Data indexing in a dataframe: Use data from ICE1
ICEdata = pd.read_csv("Downloads/ICE1_Data.csv")
print(ICEdata.head())

#Create new columns from other columns
ICEdata['some rate'] = ICEdata['graduation 2010-11'] - ICEdata['college enroll 2010-11']

#Slicing
print(ICEdata.loc[2:4]) #Using the index names
print(ICEdata.iloc[:3, :2]) #Using the index coordinates



      DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0  01M292           Developing                  C                      C   
1  01M448           Developing                  C                      B   
2  01M450       Well Developed                  A                      B   
3  01M509           Proficient                  C                      C   
4  01M539           Proficient                  A                      A   

   graduation 2010-11  college enroll 2010-11  
0               0.563                   0.519  
1               0.707                   0.363  
2               0.716                   0.692  
3               0.564                   0.477  
4               0.953                   0.870  
      DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
2  01M450       Well Developed                  A                      B   
3  01M509           Proficient                  C                      C   
4  01M539           Profici

In [8]:
#Masking
print(ICEdata[ICEdata['Progress_Rpt_10-11'] == 'A'])
print(ICEdata[(ICEdata['Progress_Rpt_10-11'] == 'A') & (ICEdata['Student_Progress_10-11'] == "B")])

        DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
2    01M450       Well Developed                  A                      B   
4    01M539           Proficient                  A                      A   
7    02M288           Proficient                  A                      B   
9    02M296           Proficient                  A                      A   
10   02M298       Well Developed                  A                      A   
..      ...                  ...                ...                    ...   
415  02M475       Well Developed                  A                      B   
416  05M692       Well Developed                  A                      B   
417  10X696       Well Developed                  A                      A   
419  10X445       Well Developed                  A                      A   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  some rate  
2 

In [9]:
# Combining data sets

#Function to make a dataframe
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)


#concatenating two dataframes
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [1, 2])
print(pd.concat([df1, df2])) #keep original index labels
print(pd.concat([df1, df2], ignore_index = True)) #reset index

    A   B
1  A1  B1
2  A2  B2
1  A1  B1
2  A2  B2
    A   B
0  A1  B1
1  A2  B2
2  A1  B1
3  A2  B2


In [15]:
#More merging of dataframes
df5 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR'],
                    'age':[30, 32, 28, 30]})
df6 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014],
                    'age': [28, 30, 32, 30]})
dfm = pd.merge(df5, df6) #The merge function looks for one or more column names between the two inputs and uses them as the key
print(dfm)

  employee        group  age  hire_date
0      Bob   Accounting   30       2008
1     Jake  Engineering   32       2012
2     Lisa  Engineering   28       2004
3      Sue           HR   30       2014


In [16]:
df7 = df7 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
dfm2 = pd.merge(df5, df7)
print(dfm2)

  employee        group  age supervisor
0      Bob   Accounting   30      Carly
1     Jake  Engineering   32      Guido
2     Lisa  Engineering   28      Guido
3      Sue           HR   30      Steve


In [20]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
pd.merge(df5, df8, left_on = 'employee', right_on = 'name').drop('name', axis = 1) #The 'drop' function deletes the redundant column after merging

employee        group  age  salary
0      Bob   Accounting   30   70000
1     Jake  Engineering   32   80000
2     Lisa  Engineering   28  120000
3      Sue           HR   30   90000

In [26]:
#aggregating functions
print(ICEdata.groupby('Quality_Review_Score').mean()) #Finding the aggregate mean for all numerical columns for each unique value in Quality_Review_Score

                                                    graduation 2010-11  \
Quality_Review_Score                                                     
Developing                                                    0.633019   
Outstanding (only an option in 2007-8)                        0.864333   
Proficient                                                    0.729554   
Underdeveloped                                                0.549667   
Underdeveloped with Proficient Features (only a...                 NaN   
Well Developed                                                0.823367   

                                                    college enroll 2010-11  \
Quality_Review_Score                                                         
Developing                                                        0.402830   
Outstanding (only an option in 2007-8)                            0.747667   
Proficient                                                        0.521208   
Underdeveloped   

In [27]:
print(ICEdata.groupby('Quality_Review_Score')['graduation 2010-11'].max()) #Finding the max value for column 'graduation 2010-11' for each unique value in Quality_Review_Score

Quality_Review_Score
Developing                                                                                0.633019
Outstanding (only an option in 2007-8)                                                    0.864333
Proficient                                                                                0.729554
Underdeveloped                                                                            0.549667
Underdeveloped with Proficient Features (only an option in 2007-8, 2008-9 and 2009-10)         NaN
Well Developed                                                                            0.823367
Name: graduation 2010-11, dtype: float64


In [28]:
ICEdata.groupby('Quality_Review_Score')['graduation 2010-11'].aggregate(['median', 'min', 'max'])

median    min    max
Quality_Review_Score                                                    
Developing                                           0.615  0.457  0.947
Outstanding (only an option in 2007-8)               0.811  0.800  0.982
Proficient                                           0.722  0.412  1.000
Underdeveloped                                       0.554  0.457  0.624
Underdeveloped with Proficient Features (only a...     NaN    NaN    NaN
Well Developed                                       0.833  0.545  1.000

In [34]:
#grouping with two columns
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11'])['graduation 2010-11'].mean()

Quality_Review_Score                    Progress_Rpt_10-11
Developing                              A                     0.716500
                                        B                     0.654545
                                        C                     0.639474
                                        D                     0.613812
                                        F                     0.504333
Outstanding (only an option in 2007-8)  A                     0.864333
Proficient                              A                     0.817083
                                        B                     0.722077
                                        C                     0.660333
                                        D                     0.526400
Underdeveloped                          C                     0.556333
                                        D                     0.457000
                                        F                     0.586000
Well Developed    

In [35]:
#representing the above table in a two-dimensional fashion
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11'])['graduation 2010-11'].mean().unstack()

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

In [40]:
#Creating the above table using the pivot table
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns=['Progress_Rpt_10-11'])

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

In [39]:
#Creating further subgroups in the above table
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns=['Progress_Rpt_10-11', 'Student_Progress_10-11'])

Progress_Rpt_10-11                             A                         B  \
Student_Progress_10-11                         A         B       C       A   
Quality_Review_Score                                                         
Developing                              0.607000  0.753000     NaN     NaN   
Outstanding (only an option in 2007-8)  0.805500  0.982000     NaN     NaN   
Proficient                              0.813259  0.817650  0.9090  0.6760   
Underdeveloped                               NaN       NaN     NaN     NaN   
Well Developed                          0.873237  0.861154  0.6665  0.8165   

Progress_Rpt_10-11                                                        C  \
Student_Progress_10-11                         B         C         D      B   
Quality_Review_Score                                                          
Developing                              0.578400  0.718000       NaN  0.707   
Outstanding (only an option in 2007-8)       NaN       NaN       NaN    NaN   
Proficient                              0.716886  0.743174  0.682333    NaN   
Underdeveloped                               NaN       NaN       NaN    NaN   
Well Developed                          0.778750  0.791333  0.833000    NaN   

Progress_Rpt_10-11                                                      D  \
Student_Progress_10-11                         C         D       F      C   
Quality_Review_Score                                                        
Developing                              0.639214  0.623500     NaN  0.643   
Outstanding (only an option in 2007-8)       NaN       NaN     NaN    NaN   
Proficient                              0.645115  0.654273  0.8915  0.412   
Underdeveloped                          0.522500  0.624000     NaN    NaN   
Well Developed                          0.713143  0.719333  0.6760    NaN   

Progress_Rpt_10-11                                               F  
Student_Progress_10-11                         D       F         F  
Quality_Review_Score                                                
Developing                              0.604889  0.6182  0.504333  
Outstanding (only an option in 2007-8)       NaN     NaN       NaN  
Proficient                              0.510000  0.6000       NaN  
Underdeveloped                          0.457000     NaN  0.586000  
Well Developed                               NaN     NaN       NaN

In [41]:
#Setting the aggregate function as max (The default is mean)
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns=['Progress_Rpt_10-11'],
                    aggfunc = 'max')

Progress_Rpt_10-11                          A      B      C      D      F
Quality_Review_Score                                                     
Developing                              0.855  0.864  0.947  0.700  0.550
Outstanding (only an option in 2007-8)  0.982    NaN    NaN    NaN    NaN
Proficient                              1.000  1.000  0.917  0.600    NaN
Underdeveloped                            NaN    NaN  0.624  0.457  0.601
Well Developed                          1.000  0.976  0.867    NaN    NaN